### ISSUE TITLE
不支持 bullseye 么？

### ISSUE THREAD

**Issue by chenmonster** [esonwong/network-rc#44]
![1669970015758](https://user-images.githubusercontent.com/34160512/205250417-7d95d7db-75d4-42d0-a4da-686f61f4e7ab.jpg)

[树莓派操作系统](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-09-26/2022-09-22-raspios-bullseye-arm64.img.xz)

**Comment by esonwong** [comment]
是的

**Comment by zoldaten** [comment]
it does not work on bullseye ?
